language: python
python:
  - "3.7"
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0

before_install:
  - sudo apt-get install -y build-essential

install:
  - pip install -r virtenv/dev_requirements.txt

script:
  - pytest
